name: Static HTML Lint/Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v3
        with:
          root: ./
